#!/bin/sh

for i in *.xlb
do
    perl -e '
        print "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n";
        print "<localizationbundle locale=\"en\">\n";

        while (<>) {
            if (/<msg/) {
                $content = $_;
            } else {
                $content .= $_;
            }

            if (/<\/msg>/) {
                $content1 = $content;
                $content1 =~ s/desc="[^"]*"//;

                unless ($seen{$content1}) {
                    print "$content";
                }

                $seen{$content1} = 1;
                $content = "";
            }
        }

        print "</localizationbundle>\n";
    ' $i ../../../../../../platform-1_0/device/data/localization/$i > /android/depot/googleclient/wireless/data/Android/$i
done
