/*
 * Copyright (C) 2016 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#undef glActiveShaderProgram
#undef glActiveShaderProgramEXT
#undef glActiveTexture
#undef glAlphaFunc
#undef glAlphaFuncQCOM
#undef glAlphaFuncx
#undef glAlphaFuncxOES
#undef glApplyFramebufferAttachmentCMAAINTEL
#undef glAttachShader
#undef glBeginConditionalRenderNV
#undef glBeginPerfMonitorAMD
#undef glBeginPerfQueryINTEL
#undef glBeginQuery
#undef glBeginQueryEXT
#undef glBeginTransformFeedback
#undef glBindAttribLocation
#undef glBindBuffer
#undef glBindBufferBase
#undef glBindBufferRange
#undef glBindFragDataLocationEXT
#undef glBindFragDataLocationIndexedEXT
#undef glBindFramebuffer
#undef glBindFramebufferOES
#undef glBindImageTexture
#undef glBindProgramPipeline
#undef glBindProgramPipelineEXT
#undef glBindRenderbuffer
#undef glBindRenderbufferOES
#undef glBindSampler
#undef glBindTexture
#undef glBindTransformFeedback
#undef glBindVertexArray
#undef glBindVertexArrayOES
#undef glBindVertexBuffer
#undef glBlendBarrier
#undef glBlendBarrierKHR
#undef glBlendBarrierNV
#undef glBlendColor
#undef glBlendEquation
#undef glBlendEquationOES
#undef glBlendEquationSeparate
#undef glBlendEquationSeparateOES
#undef glBlendEquationSeparatei
#undef glBlendEquationSeparateiEXT
#undef glBlendEquationSeparateiOES
#undef glBlendEquationi
#undef glBlendEquationiEXT
#undef glBlendEquationiOES
#undef glBlendFunc
#undef glBlendFuncSeparate
#undef glBlendFuncSeparateOES
#undef glBlendFuncSeparatei
#undef glBlendFuncSeparateiEXT
#undef glBlendFuncSeparateiOES
#undef glBlendFunci
#undef glBlendFunciEXT
#undef glBlendFunciOES
#undef glBlendParameteriNV
#undef glBlitFramebuffer
#undef glBlitFramebufferANGLE
#undef glBlitFramebufferNV
#undef glBufferData
#undef glBufferStorageEXT
#undef glBufferSubData
#undef glCheckFramebufferStatus
#undef glCheckFramebufferStatusOES
#undef glClear
#undef glClearBufferfi
#undef glClearBufferfv
#undef glClearBufferiv
#undef glClearBufferuiv
#undef glClearColor
#undef glClearColorx
#undef glClearColorxOES
#undef glClearDepthf
#undef glClearDepthfOES
#undef glClearDepthx
#undef glClearDepthxOES
#undef glClearStencil
#undef glClientActiveTexture
#undef glClientWaitSync
#undef glClientWaitSyncAPPLE
#undef glClipPlanef
#undef glClipPlanefIMG
#undef glClipPlanefOES
#undef glClipPlanex
#undef glClipPlanexIMG
#undef glClipPlanexOES
#undef glColor4f
#undef glColor4ub
#undef glColor4x
#undef glColor4xOES
#undef glColorMask
#undef glColorMaski
#undef glColorMaskiEXT
#undef glColorMaskiOES
#undef glColorPointer
#undef glCompileShader
#undef glCompressedTexImage2D
#undef glCompressedTexImage3D
#undef glCompressedTexImage3DOES
#undef glCompressedTexSubImage2D
#undef glCompressedTexSubImage3D
#undef glCompressedTexSubImage3DOES
#undef glCopyBufferSubData
#undef glCopyBufferSubDataNV
#undef glCopyImageSubData
#undef glCopyImageSubDataEXT
#undef glCopyImageSubDataOES
#undef glCopyPathNV
#undef glCopyTexImage2D
#undef glCopyTexSubImage2D
#undef glCopyTexSubImage3D
#undef glCopyTexSubImage3DOES
#undef glCopyTextureLevelsAPPLE
#undef glCoverFillPathInstancedNV
#undef glCoverFillPathNV
#undef glCoverStrokePathInstancedNV
#undef glCoverStrokePathNV
#undef glCoverageMaskNV
#undef glCoverageModulationNV
#undef glCoverageModulationTableNV
#undef glCoverageOperationNV
#undef glCreatePerfQueryINTEL
#undef glCreateProgram
#undef glCreateShader
#undef glCreateShaderProgramv
#undef glCreateShaderProgramvEXT
#undef glCullFace
#undef glCurrentPaletteMatrixOES
#undef glDebugMessageCallback
#undef glDebugMessageCallbackKHR
#undef glDebugMessageControl
#undef glDebugMessageControlKHR
#undef glDebugMessageInsert
#undef glDebugMessageInsertKHR
#undef glDeleteBuffers
#undef glDeleteFencesNV
#undef glDeleteFramebuffers
#undef glDeleteFramebuffersOES
#undef glDeletePathsNV
#undef glDeletePerfMonitorsAMD
#undef glDeletePerfQueryINTEL
#undef glDeleteProgram
#undef glDeleteProgramPipelines
#undef glDeleteProgramPipelinesEXT
#undef glDeleteQueries
#undef glDeleteQueriesEXT
#undef glDeleteRenderbuffers
#undef glDeleteRenderbuffersOES
#undef glDeleteSamplers
#undef glDeleteShader
#undef glDeleteSync
#undef glDeleteSyncAPPLE
#undef glDeleteTextures
#undef glDeleteTransformFeedbacks
#undef glDeleteVertexArrays
#undef glDeleteVertexArraysOES
#undef glDepthFunc
#undef glDepthMask
#undef glDepthRangeArrayfvNV
#undef glDepthRangeIndexedfNV
#undef glDepthRangef
#undef glDepthRangefOES
#undef glDepthRangex
#undef glDepthRangexOES
#undef glDetachShader
#undef glDisable
#undef glDisableClientState
#undef glDisableDriverControlQCOM
#undef glDisableVertexAttribArray
#undef glDisablei
#undef glDisableiEXT
#undef glDisableiNV
#undef glDisableiOES
#undef glDiscardFramebufferEXT
#undef glDispatchCompute
#undef glDispatchComputeIndirect
#undef glDrawArrays
#undef glDrawArraysIndirect
#undef glDrawArraysInstanced
#undef glDrawArraysInstancedANGLE
#undef glDrawArraysInstancedBaseInstanceEXT
#undef glDrawArraysInstancedEXT
#undef glDrawArraysInstancedNV
#undef glDrawBuffers
#undef glDrawBuffersEXT
#undef glDrawBuffersIndexedEXT
#undef glDrawBuffersNV
#undef glDrawElements
#undef glDrawElementsBaseVertex
#undef glDrawElementsBaseVertexEXT
#undef glDrawElementsBaseVertexOES
#undef glDrawElementsIndirect
#undef glDrawElementsInstanced
#undef glDrawElementsInstancedANGLE
#undef glDrawElementsInstancedBaseInstanceEXT
#undef glDrawElementsInstancedBaseVertex
#undef glDrawElementsInstancedBaseVertexBaseInstanceEXT
#undef glDrawElementsInstancedBaseVertexEXT
#undef glDrawElementsInstancedBaseVertexOES
#undef glDrawElementsInstancedEXT
#undef glDrawElementsInstancedNV
#undef glDrawRangeElements
#undef glDrawRangeElementsBaseVertex
#undef glDrawRangeElementsBaseVertexEXT
#undef glDrawRangeElementsBaseVertexOES
#undef glDrawTexfOES
#undef glDrawTexfvOES
#undef glDrawTexiOES
#undef glDrawTexivOES
#undef glDrawTexsOES
#undef glDrawTexsvOES
#undef glDrawTexxOES
#undef glDrawTexxvOES
#undef glEGLImageTargetRenderbufferStorageOES
#undef glEGLImageTargetTexture2DOES
#undef glEnable
#undef glEnableClientState
#undef glEnableDriverControlQCOM
#undef glEnableVertexAttribArray
#undef glEnablei
#undef glEnableiEXT
#undef glEnableiNV
#undef glEnableiOES
#undef glEndConditionalRenderNV
#undef glEndPerfMonitorAMD
#undef glEndPerfQueryINTEL
#undef glEndQuery
#undef glEndQueryEXT
#undef glEndTilingQCOM
#undef glEndTransformFeedback
#undef glExtGetBufferPointervQCOM
#undef glExtGetBuffersQCOM
#undef glExtGetFramebuffersQCOM
#undef glExtGetProgramBinarySourceQCOM
#undef glExtGetProgramsQCOM
#undef glExtGetRenderbuffersQCOM
#undef glExtGetShadersQCOM
#undef glExtGetTexLevelParameterivQCOM
#undef glExtGetTexSubImageQCOM
#undef glExtGetTexturesQCOM
#undef glExtIsProgramBinaryQCOM
#undef glExtTexObjectStateOverrideiQCOM
#undef glFenceSync
#undef glFenceSyncAPPLE
#undef glFinish
#undef glFinishFenceNV
#undef glFlush
#undef glFlushMappedBufferRange
#undef glFlushMappedBufferRangeEXT
#undef glFogf
#undef glFogfv
#undef glFogx
#undef glFogxOES
#undef glFogxv
#undef glFogxvOES
#undef glFragmentCoverageColorNV
#undef glFramebufferParameteri
#undef glFramebufferRenderbuffer
#undef glFramebufferRenderbufferOES
#undef glFramebufferSampleLocationsfvNV
#undef glFramebufferTexture
#undef glFramebufferTexture2D
#undef glFramebufferTexture2DMultisampleEXT
#undef glFramebufferTexture2DMultisampleIMG
#undef glFramebufferTexture2DOES
#undef glFramebufferTexture3DOES
#undef glFramebufferTextureEXT
#undef glFramebufferTextureLayer
#undef glFramebufferTextureMultisampleMultiviewOVR
#undef glFramebufferTextureMultiviewOVR
#undef glFramebufferTextureOES
#undef glFrontFace
#undef glFrustumf
#undef glFrustumfOES
#undef glFrustumx
#undef glFrustumxOES
#undef glGenBuffers
#undef glGenFencesNV
#undef glGenFramebuffers
#undef glGenFramebuffersOES
#undef glGenPathsNV
#undef glGenPerfMonitorsAMD
#undef glGenProgramPipelines
#undef glGenProgramPipelinesEXT
#undef glGenQueries
#undef glGenQueriesEXT
#undef glGenRenderbuffers
#undef glGenRenderbuffersOES
#undef glGenSamplers
#undef glGenTextures
#undef glGenTransformFeedbacks
#undef glGenVertexArrays
#undef glGenVertexArraysOES
#undef glGenerateMipmap
#undef glGenerateMipmapOES
#undef glGetActiveAttrib
#undef glGetActiveUniform
#undef glGetActiveUniformBlockName
#undef glGetActiveUniformBlockiv
#undef glGetActiveUniformsiv
#undef glGetAttachedShaders
#undef glGetAttribLocation
#undef glGetBooleani_v
#undef glGetBooleanv
#undef glGetBufferParameteri64v
#undef glGetBufferParameteriv
#undef glGetBufferPointerv
#undef glGetBufferPointervOES
#undef glGetClipPlanef
#undef glGetClipPlanefOES
#undef glGetClipPlanex
#undef glGetClipPlanexOES
#undef glGetCoverageModulationTableNV
#undef glGetDebugMessageLog
#undef glGetDebugMessageLogKHR
#undef glGetDriverControlStringQCOM
#undef glGetDriverControlsQCOM
#undef glGetError
#undef glGetFenceivNV
#undef glGetFirstPerfQueryIdINTEL
#undef glGetFixedv
#undef glGetFixedvOES
#undef glGetFloati_vNV
#undef glGetFloatv
#undef glGetFragDataIndexEXT
#undef glGetFragDataLocation
#undef glGetFramebufferAttachmentParameteriv
#undef glGetFramebufferAttachmentParameterivOES
#undef glGetFramebufferParameteriv
#undef glGetGraphicsResetStatus
#undef glGetGraphicsResetStatusEXT
#undef glGetGraphicsResetStatusKHR
#undef glGetImageHandleNV
#undef glGetInteger64i_v
#undef glGetInteger64v
#undef glGetInteger64vAPPLE
#undef glGetIntegeri_v
#undef glGetIntegeri_vEXT
#undef glGetIntegerv
#undef glGetInternalformatSampleivNV
#undef glGetInternalformativ
#undef glGetLightfv
#undef glGetLightxv
#undef glGetLightxvOES
#undef glGetMaterialfv
#undef glGetMaterialxv
#undef glGetMaterialxvOES
#undef glGetMultisamplefv
#undef glGetNextPerfQueryIdINTEL
#undef glGetObjectLabel
#undef glGetObjectLabelEXT
#undef glGetObjectLabelKHR
#undef glGetObjectPtrLabel
#undef glGetObjectPtrLabelKHR
#undef glGetPathCommandsNV
#undef glGetPathCoordsNV
#undef glGetPathDashArrayNV
#undef glGetPathLengthNV
#undef glGetPathMetricRangeNV
#undef glGetPathMetricsNV
#undef glGetPathParameterfvNV
#undef glGetPathParameterivNV
#undef glGetPathSpacingNV
#undef glGetPerfCounterInfoINTEL
#undef glGetPerfMonitorCounterDataAMD
#undef glGetPerfMonitorCounterInfoAMD
#undef glGetPerfMonitorCounterStringAMD
#undef glGetPerfMonitorCountersAMD
#undef glGetPerfMonitorGroupStringAMD
#undef glGetPerfMonitorGroupsAMD
#undef glGetPerfQueryDataINTEL
#undef glGetPerfQueryIdByNameINTEL
#undef glGetPerfQueryInfoINTEL
#undef glGetPointerv
#undef glGetPointervKHR
#undef glGetProgramBinary
#undef glGetProgramBinaryOES
#undef glGetProgramInfoLog
#undef glGetProgramInterfaceiv
#undef glGetProgramPipelineInfoLog
#undef glGetProgramPipelineInfoLogEXT
#undef glGetProgramPipelineiv
#undef glGetProgramPipelineivEXT
#undef glGetProgramResourceIndex
#undef glGetProgramResourceLocation
#undef glGetProgramResourceLocationIndexEXT
#undef glGetProgramResourceName
#undef glGetProgramResourcefvNV
#undef glGetProgramResourceiv
#undef glGetProgramiv
#undef glGetQueryObjecti64vEXT
#undef glGetQueryObjectivEXT
#undef glGetQueryObjectui64vEXT
#undef glGetQueryObjectuiv
#undef glGetQueryObjectuivEXT
#undef glGetQueryiv
#undef glGetQueryivEXT
#undef glGetRenderbufferParameteriv
#undef glGetRenderbufferParameterivOES
#undef glGetSamplerParameterIiv
#undef glGetSamplerParameterIivEXT
#undef glGetSamplerParameterIivOES
#undef glGetSamplerParameterIuiv
#undef glGetSamplerParameterIuivEXT
#undef glGetSamplerParameterIuivOES
#undef glGetSamplerParameterfv
#undef glGetSamplerParameteriv
#undef glGetShaderInfoLog
#undef glGetShaderPrecisionFormat
#undef glGetShaderSource
#undef glGetShaderiv
#undef glGetString
#undef glGetStringi
#undef glGetSynciv
#undef glGetSyncivAPPLE
#undef glGetTexEnvfv
#undef glGetTexEnviv
#undef glGetTexEnvxv
#undef glGetTexEnvxvOES
#undef glGetTexGenfvOES
#undef glGetTexGenivOES
#undef glGetTexGenxvOES
#undef glGetTexLevelParameterfv
#undef glGetTexLevelParameteriv
#undef glGetTexParameterIiv
#undef glGetTexParameterIivEXT
#undef glGetTexParameterIivOES
#undef glGetTexParameterIuiv
#undef glGetTexParameterIuivEXT
#undef glGetTexParameterIuivOES
#undef glGetTexParameterfv
#undef glGetTexParameteriv
#undef glGetTexParameterxv
#undef glGetTexParameterxvOES
#undef glGetTextureHandleNV
#undef glGetTextureSamplerHandleNV
#undef glGetTransformFeedbackVarying
#undef glGetTranslatedShaderSourceANGLE
#undef glGetUniformBlockIndex
#undef glGetUniformIndices
#undef glGetUniformLocation
#undef glGetUniformfv
#undef glGetUniformiv
#undef glGetUniformuiv
#undef glGetVertexAttribIiv
#undef glGetVertexAttribIuiv
#undef glGetVertexAttribPointerv
#undef glGetVertexAttribfv
#undef glGetVertexAttribiv
#undef glGetnUniformfv
#undef glGetnUniformfvEXT
#undef glGetnUniformfvKHR
#undef glGetnUniformiv
#undef glGetnUniformivEXT
#undef glGetnUniformivKHR
#undef glGetnUniformuiv
#undef glGetnUniformuivKHR
#undef glHint
#undef glInsertEventMarkerEXT
#undef glInterpolatePathsNV
#undef glInvalidateFramebuffer
#undef glInvalidateSubFramebuffer
#undef glIsBuffer
#undef glIsEnabled
#undef glIsEnabledi
#undef glIsEnablediEXT
#undef glIsEnablediNV
#undef glIsEnablediOES
#undef glIsFenceNV
#undef glIsFramebuffer
#undef glIsFramebufferOES
#undef glIsImageHandleResidentNV
#undef glIsPathNV
#undef glIsPointInFillPathNV
#undef glIsPointInStrokePathNV
#undef glIsProgram
#undef glIsProgramPipeline
#undef glIsProgramPipelineEXT
#undef glIsQuery
#undef glIsQueryEXT
#undef glIsRenderbuffer
#undef glIsRenderbufferOES
#undef glIsSampler
#undef glIsShader
#undef glIsSync
#undef glIsSyncAPPLE
#undef glIsTexture
#undef glIsTextureHandleResidentNV
#undef glIsTransformFeedback
#undef glIsVertexArray
#undef glIsVertexArrayOES
#undef glLabelObjectEXT
#undef glLightModelf
#undef glLightModelfv
#undef glLightModelx
#undef glLightModelxOES
#undef glLightModelxv
#undef glLightModelxvOES
#undef glLightf
#undef glLightfv
#undef glLightx
#undef glLightxOES
#undef glLightxv
#undef glLightxvOES
#undef glLineWidth
#undef glLineWidthx
#undef glLineWidthxOES
#undef glLinkProgram
#undef glLoadIdentity
#undef glLoadMatrixf
#undef glLoadMatrixx
#undef glLoadMatrixxOES
#undef glLoadPaletteFromModelViewMatrixOES
#undef glLogicOp
#undef glMakeImageHandleNonResidentNV
#undef glMakeImageHandleResidentNV
#undef glMakeTextureHandleNonResidentNV
#undef glMakeTextureHandleResidentNV
#undef glMapBufferOES
#undef glMapBufferRange
#undef glMapBufferRangeEXT
#undef glMaterialf
#undef glMaterialfv
#undef glMaterialx
#undef glMaterialxOES
#undef glMaterialxv
#undef glMaterialxvOES
#undef glMatrixIndexPointerOES
#undef glMatrixLoad3x2fNV
#undef glMatrixLoad3x3fNV
#undef glMatrixLoadTranspose3x3fNV
#undef glMatrixMode
#undef glMatrixMult3x2fNV
#undef glMatrixMult3x3fNV
#undef glMatrixMultTranspose3x3fNV
#undef glMemoryBarrier
#undef glMemoryBarrierByRegion
#undef glMinSampleShading
#undef glMinSampleShadingOES
#undef glMultMatrixf
#undef glMultMatrixx
#undef glMultMatrixxOES
#undef glMultiDrawArraysEXT
#undef glMultiDrawArraysIndirectEXT
#undef glMultiDrawElementsBaseVertexEXT
#undef glMultiDrawElementsBaseVertexOES
#undef glMultiDrawElementsEXT
#undef glMultiDrawElementsIndirectEXT
#undef glMultiTexCoord4f
#undef glMultiTexCoord4x
#undef glMultiTexCoord4xOES
#undef glNamedFramebufferSampleLocationsfvNV
#undef glNormal3f
#undef glNormal3x
#undef glNormal3xOES
#undef glNormalPointer
#undef glObjectLabel
#undef glObjectLabelKHR
#undef glObjectPtrLabel
#undef glObjectPtrLabelKHR
#undef glOrthof
#undef glOrthofOES
#undef glOrthox
#undef glOrthoxOES
#undef glPatchParameteri
#undef glPatchParameteriEXT
#undef glPatchParameteriOES
#undef glPathCommandsNV
#undef glPathCoordsNV
#undef glPathCoverDepthFuncNV
#undef glPathDashArrayNV
#undef glPathGlyphIndexArrayNV
#undef glPathGlyphIndexRangeNV
#undef glPathGlyphRangeNV
#undef glPathGlyphsNV
#undef glPathMemoryGlyphIndexArrayNV
#undef glPathParameterfNV
#undef glPathParameterfvNV
#undef glPathParameteriNV
#undef glPathParameterivNV
#undef glPathStencilDepthOffsetNV
#undef glPathStencilFuncNV
#undef glPathStringNV
#undef glPathSubCommandsNV
#undef glPathSubCoordsNV
#undef glPauseTransformFeedback
#undef glPixelStorei
#undef glPointAlongPathNV
#undef glPointParameterf
#undef glPointParameterfv
#undef glPointParameterx
#undef glPointParameterxOES
#undef glPointParameterxv
#undef glPointParameterxvOES
#undef glPointSize
#undef glPointSizePointerOES
#undef glPointSizex
#undef glPointSizexOES
#undef glPolygonModeNV
#undef glPolygonOffset
#undef glPolygonOffsetx
#undef glPolygonOffsetxOES
#undef glPopDebugGroup
#undef glPopDebugGroupKHR
#undef glPopGroupMarkerEXT
#undef glPopMatrix
#undef glPrimitiveBoundingBox
#undef glPrimitiveBoundingBoxEXT
#undef glPrimitiveBoundingBoxOES
#undef glProgramBinary
#undef glProgramBinaryOES
#undef glProgramParameteri
#undef glProgramParameteriEXT
#undef glProgramPathFragmentInputGenNV
#undef glProgramUniform1f
#undef glProgramUniform1fEXT
#undef glProgramUniform1fv
#undef glProgramUniform1fvEXT
#undef glProgramUniform1i
#undef glProgramUniform1iEXT
#undef glProgramUniform1iv
#undef glProgramUniform1ivEXT
#undef glProgramUniform1ui
#undef glProgramUniform1uiEXT
#undef glProgramUniform1uiv
#undef glProgramUniform1uivEXT
#undef glProgramUniform2f
#undef glProgramUniform2fEXT
#undef glProgramUniform2fv
#undef glProgramUniform2fvEXT
#undef glProgramUniform2i
#undef glProgramUniform2iEXT
#undef glProgramUniform2iv
#undef glProgramUniform2ivEXT
#undef glProgramUniform2ui
#undef glProgramUniform2uiEXT
#undef glProgramUniform2uiv
#undef glProgramUniform2uivEXT
#undef glProgramUniform3f
#undef glProgramUniform3fEXT
#undef glProgramUniform3fv
#undef glProgramUniform3fvEXT
#undef glProgramUniform3i
#undef glProgramUniform3iEXT
#undef glProgramUniform3iv
#undef glProgramUniform3ivEXT
#undef glProgramUniform3ui
#undef glProgramUniform3uiEXT
#undef glProgramUniform3uiv
#undef glProgramUniform3uivEXT
#undef glProgramUniform4f
#undef glProgramUniform4fEXT
#undef glProgramUniform4fv
#undef glProgramUniform4fvEXT
#undef glProgramUniform4i
#undef glProgramUniform4iEXT
#undef glProgramUniform4iv
#undef glProgramUniform4ivEXT
#undef glProgramUniform4ui
#undef glProgramUniform4uiEXT
#undef glProgramUniform4uiv
#undef glProgramUniform4uivEXT
#undef glProgramUniformHandleui64NV
#undef glProgramUniformHandleui64vNV
#undef glProgramUniformMatrix2fv
#undef glProgramUniformMatrix2fvEXT
#undef glProgramUniformMatrix2x3fv
#undef glProgramUniformMatrix2x3fvEXT
#undef glProgramUniformMatrix2x4fv
#undef glProgramUniformMatrix2x4fvEXT
#undef glProgramUniformMatrix3fv
#undef glProgramUniformMatrix3fvEXT
#undef glProgramUniformMatrix3x2fv
#undef glProgramUniformMatrix3x2fvEXT
#undef glProgramUniformMatrix3x4fv
#undef glProgramUniformMatrix3x4fvEXT
#undef glProgramUniformMatrix4fv
#undef glProgramUniformMatrix4fvEXT
#undef glProgramUniformMatrix4x2fv
#undef glProgramUniformMatrix4x2fvEXT
#undef glProgramUniformMatrix4x3fv
#undef glProgramUniformMatrix4x3fvEXT
#undef glPushDebugGroup
#undef glPushDebugGroupKHR
#undef glPushGroupMarkerEXT
#undef glPushMatrix
#undef glQueryCounterEXT
#undef glQueryMatrixxOES
#undef glRasterSamplesEXT
#undef glReadBuffer
#undef glReadBufferIndexedEXT
#undef glReadBufferNV
#undef glReadPixels
#undef glReadnPixels
#undef glReadnPixelsEXT
#undef glReadnPixelsKHR
#undef glReleaseShaderCompiler
#undef glRenderbufferStorage
#undef glRenderbufferStorageMultisample
#undef glRenderbufferStorageMultisampleANGLE
#undef glRenderbufferStorageMultisampleAPPLE
#undef glRenderbufferStorageMultisampleEXT
#undef glRenderbufferStorageMultisampleIMG
#undef glRenderbufferStorageMultisampleNV
#undef glRenderbufferStorageOES
#undef glResolveDepthValuesNV
#undef glResolveMultisampleFramebufferAPPLE
#undef glResumeTransformFeedback
#undef glRotatef
#undef glRotatex
#undef glRotatexOES
#undef glSampleCoverage
#undef glSampleCoveragex
#undef glSampleCoveragexOES
#undef glSampleMaski
#undef glSamplerParameterIiv
#undef glSamplerParameterIivEXT
#undef glSamplerParameterIivOES
#undef glSamplerParameterIuiv
#undef glSamplerParameterIuivEXT
#undef glSamplerParameterIuivOES
#undef glSamplerParameterf
#undef glSamplerParameterfv
#undef glSamplerParameteri
#undef glSamplerParameteriv
#undef glScalef
#undef glScalex
#undef glScalexOES
#undef glScissor
#undef glScissorArrayvNV
#undef glScissorIndexedNV
#undef glScissorIndexedvNV
#undef glSelectPerfMonitorCountersAMD
#undef glSetFenceNV
#undef glShadeModel
#undef glShaderBinary
#undef glShaderSource
#undef glStartTilingQCOM
#undef glStencilFillPathInstancedNV
#undef glStencilFillPathNV
#undef glStencilFunc
#undef glStencilFuncSeparate
#undef glStencilMask
#undef glStencilMaskSeparate
#undef glStencilOp
#undef glStencilOpSeparate
#undef glStencilStrokePathInstancedNV
#undef glStencilStrokePathNV
#undef glStencilThenCoverFillPathInstancedNV
#undef glStencilThenCoverFillPathNV
#undef glStencilThenCoverStrokePathInstancedNV
#undef glStencilThenCoverStrokePathNV
#undef glSubpixelPrecisionBiasNV
#undef glTestFenceNV
#undef glTexBuffer
#undef glTexBufferEXT
#undef glTexBufferOES
#undef glTexBufferRange
#undef glTexBufferRangeEXT
#undef glTexBufferRangeOES
#undef glTexCoordPointer
#undef glTexEnvf
#undef glTexEnvfv
#undef glTexEnvi
#undef glTexEnviv
#undef glTexEnvx
#undef glTexEnvxOES
#undef glTexEnvxv
#undef glTexEnvxvOES
#undef glTexGenfOES
#undef glTexGenfvOES
#undef glTexGeniOES
#undef glTexGenivOES
#undef glTexGenxOES
#undef glTexGenxvOES
#undef glTexImage2D
#undef glTexImage3D
#undef glTexImage3DOES
#undef glTexPageCommitmentEXT
#undef glTexParameterIiv
#undef glTexParameterIivEXT
#undef glTexParameterIivOES
#undef glTexParameterIuiv
#undef glTexParameterIuivEXT
#undef glTexParameterIuivOES
#undef glTexParameterf
#undef glTexParameterfv
#undef glTexParameteri
#undef glTexParameteriv
#undef glTexParameterx
#undef glTexParameterxOES
#undef glTexParameterxv
#undef glTexParameterxvOES
#undef glTexStorage1DEXT
#undef glTexStorage2D
#undef glTexStorage2DEXT
#undef glTexStorage2DMultisample
#undef glTexStorage3D
#undef glTexStorage3DEXT
#undef glTexStorage3DMultisample
#undef glTexStorage3DMultisampleOES
#undef glTexSubImage2D
#undef glTexSubImage3D
#undef glTexSubImage3DOES
#undef glTextureStorage1DEXT
#undef glTextureStorage2DEXT
#undef glTextureStorage3DEXT
#undef glTextureViewEXT
#undef glTextureViewOES
#undef glTransformFeedbackVaryings
#undef glTransformPathNV
#undef glTranslatef
#undef glTranslatex
#undef glTranslatexOES
#undef glUniform1f
#undef glUniform1fv
#undef glUniform1i
#undef glUniform1iv
#undef glUniform1ui
#undef glUniform1uiv
#undef glUniform2f
#undef glUniform2fv
#undef glUniform2i
#undef glUniform2iv
#undef glUniform2ui
#undef glUniform2uiv
#undef glUniform3f
#undef glUniform3fv
#undef glUniform3i
#undef glUniform3iv
#undef glUniform3ui
#undef glUniform3uiv
#undef glUniform4f
#undef glUniform4fv
#undef glUniform4i
#undef glUniform4iv
#undef glUniform4ui
#undef glUniform4uiv
#undef glUniformBlockBinding
#undef glUniformHandleui64NV
#undef glUniformHandleui64vNV
#undef glUniformMatrix2fv
#undef glUniformMatrix2x3fv
#undef glUniformMatrix2x3fvNV
#undef glUniformMatrix2x4fv
#undef glUniformMatrix2x4fvNV
#undef glUniformMatrix3fv
#undef glUniformMatrix3x2fv
#undef glUniformMatrix3x2fvNV
#undef glUniformMatrix3x4fv
#undef glUniformMatrix3x4fvNV
#undef glUniformMatrix4fv
#undef glUniformMatrix4x2fv
#undef glUniformMatrix4x2fvNV
#undef glUniformMatrix4x3fv
#undef glUniformMatrix4x3fvNV
#undef glUnmapBuffer
#undef glUnmapBufferOES
#undef glUseProgram
#undef glUseProgramStages
#undef glUseProgramStagesEXT
#undef glValidateProgram
#undef glValidateProgramPipeline
#undef glValidateProgramPipelineEXT
#undef glVertexAttrib1f
#undef glVertexAttrib1fv
#undef glVertexAttrib2f
#undef glVertexAttrib2fv
#undef glVertexAttrib3f
#undef glVertexAttrib3fv
#undef glVertexAttrib4f
#undef glVertexAttrib4fv
#undef glVertexAttribBinding
#undef glVertexAttribDivisor
#undef glVertexAttribDivisorANGLE
#undef glVertexAttribDivisorEXT
#undef glVertexAttribDivisorNV
#undef glVertexAttribFormat
#undef glVertexAttribI4i
#undef glVertexAttribI4iv
#undef glVertexAttribI4ui
#undef glVertexAttribI4uiv
#undef glVertexAttribIFormat
#undef glVertexAttribIPointer
#undef glVertexAttribPointer
#undef glVertexBindingDivisor
#undef glVertexPointer
#undef glViewport
#undef glViewportArrayvNV
#undef glViewportIndexedfNV
#undef glViewportIndexedfvNV
#undef glWaitSync
#undef glWaitSyncAPPLE
#undef glWeightPathsNV
#undef glWeightPointerOES
