package android.content.res;

public class HoloResources {
	public static String HoloResources[] = { "btn_cab_done_holo_dark.xml",
			"btn_cab_done_holo_light.xml", "btn_check_holo_dark.xml",
			"btn_check_holo_light.xml", "btn_group_holo_dark.xml",
			"btn_group_holo_light.xml", "btn_radio_holo_dark.xml",
			"btn_radio_holo_light.xml", "btn_star_holo_dark.xml",
			"btn_star_holo_light.xml", "edit_text_holo_dark.xml",
			"edit_text_holo_light.xml", "expander_group_holo_dark.xml",
			"expander_group_holo_light.xml", "fastscroll_thumb_holo.xml",
			"fastscroll_track_holo_dark.xml",
			"fastscroll_track_holo_light.xml", "ic_clear_holo_light.xml",
			"ic_media_route_connecting_holo_dark.xml",
			"ic_media_route_connecting_holo_light.xml",
			"ic_media_route_holo_dark.xml", "ic_media_route_holo_light.xml",
			"progress_horizontal_holo_dark.xml",
			"progress_horizontal_holo_light.xml",
			"progress_indeterminate_horizontal_holo.xml",
			"progress_large_holo.xml", "progress_medium_holo.xml",
			"progress_small_holo.xml", "ratingbar_full_empty_holo_dark.xml",
			"ratingbar_full_empty_holo_light.xml",
			"ratingbar_full_filled_holo_dark.xml",
			"ratingbar_full_filled_holo_light.xml",
			"ratingbar_full_holo_dark.xml", "ratingbar_full_holo_light.xml",
			"ratingbar_holo_dark.xml", "ratingbar_holo_light.xml",
			"ratingbar_small_holo_dark.xml", "ratingbar_small_holo_light.xml",
			"scrubber_control_selector_holo.xml",
			"scrubber_progress_horizontal_holo_dark.xml",
			"scrubber_progress_horizontal_holo_light.xml",
			"spinner_ab_holo_dark.xml", "spinner_ab_holo_light.xml",
			"switch_inner_holo_dark.xml", "switch_inner_holo_light.xml",
			"switch_track_holo_dark.xml", "switch_track_holo_light.xml",
			"tab_indicator_ab_holo.xml", "tab_indicator_holo.xml",
			"textfield_searchview_holo_dark.xml",
			"textfield_searchview_holo_light.xml",
			"textfield_searchview_right_holo_dark.xml",
			"textfield_searchview_right_holo_light.xml",
			"ab_bottom_transparent_dark_holo.9.png",
			"ab_bottom_transparent_light_holo.9.png",
			"ab_share_pack_holo_dark.9.png", "ab_share_pack_holo_light.9.png",
			"btn_cab_done_default_holo_dark.9.png",
			"btn_cab_done_default_holo_light.9.png",
			"btn_cab_done_focused_holo_dark.9.png",
			"btn_cab_done_focused_holo_light.9.png",
			"btn_cab_done_pressed_holo_dark.9.png",
			"btn_cab_done_pressed_holo_light.9.png",
			"btn_check_on_disable_focused_holo_light.png",
			"btn_check_on_disable_holo_dark.png",
			"btn_check_on_disable_holo_light.png",
			"btn_check_on_disabled_focused_holo_dark.png",
			"btn_check_on_disabled_focused_holo_light.png",
			"btn_check_on_disabled_holo_dark.png",
			"btn_check_on_disabled_holo_light.png",
			"btn_check_on_focused_holo_dark.png",
			"btn_check_on_focused_holo_light.png", "btn_check_on_holo.png",
			"btn_check_on_holo_dark.png", "btn_check_on_holo_light.png",
			"btn_check_on_pressed_holo_dark.png",
			"btn_check_on_pressed_holo_light.png",
			"btn_code_lock_default_holo.png", "btn_code_lock_touched_holo.png",
			"btn_default_focused_holo.9.png",
			"btn_default_focused_holo_dark.9.png",
			"btn_default_focused_holo_light.9.png",
			"btn_default_normal_holo.9.png",
			"btn_default_normal_holo_dark.9.png",
			"btn_default_normal_holo_light.9.png",
			"btn_default_pressed_holo.9.png",
			"btn_default_pressed_holo_dark.9.png",
			"btn_default_pressed_holo_light.9.png",
			"btn_group_disabled_holo_dark.9.png",
			"btn_group_disabled_holo_light.9.png",
			"btn_group_focused_holo_dark.9.png",
			"btn_group_focused_holo_light.9.png",
			"btn_group_normal_holo_dark.9.png",
			"btn_group_normal_holo_light.9.png",
			"btn_group_pressed_holo_dark.9.png",
			"btn_group_pressed_holo_light.9.png",
			"btn_keyboard_key_dark_normal_holo.9.png",
			"btn_keyboard_key_dark_normal_off_holo.9.png",
			"btn_keyboard_key_dark_normal_on_holo.9.png",
			"btn_keyboard_key_dark_pressed_holo.9.png",
			"btn_keyboard_key_dark_pressed_off_holo.9.png",
			"btn_keyboard_key_dark_pressed_on_holo.9.png",
			"btn_keyboard_key_light_normal_holo.9.png",
			"btn_keyboard_key_light_pressed_holo.9.png",
			"btn_radio_off_disabled_focused_holo_dark.png",
			"btn_radio_off_disabled_focused_holo_light.png",
			"btn_radio_off_disabled_holo_dark.png",
			"btn_radio_off_disabled_holo_light.png",
			"btn_radio_off_focused_holo_dark.png",
			"btn_radio_off_focused_holo_light.png", "btn_radio_off_holo.png",
			"btn_radio_off_holo_dark.png", "btn_radio_off_holo_light.png",
			"btn_radio_off_pressed_holo_dark.png",
			"btn_radio_off_pressed_holo_light.png",
			"btn_radio_on_disabled_focused_holo_dark.png",
			"btn_radio_on_disabled_focused_holo_light.png",
			"btn_radio_on_disabled_holo_dark.png",
			"btn_radio_on_disabled_holo_light.png",
			"btn_radio_on_focused_holo_dark.png",
			"btn_radio_on_focused_holo_light.png", "btn_radio_on_holo.png",
			"btn_radio_on_holo_dark.png", "btn_radio_on_holo_light.png",
			"btn_radio_on_pressed_holo_dark.png",
			"btn_radio_on_pressed_holo_light.png",
			"btn_rating_star_off_disabled_focused_holo_dark.png",
			"btn_rating_star_off_disabled_focused_holo_light.png",
			"btn_rating_star_off_disabled_holo_dark.png",
			"btn_rating_star_off_disabled_holo_light.png",
			"btn_rating_star_off_focused_holo_dark.png",
			"btn_rating_star_off_focused_holo_light.png",
			"btn_rating_star_off_normal_holo_dark.png",
			"btn_rating_star_off_normal_holo_light.png",
			"btn_rating_star_off_pressed_holo_dark.png",
			"btn_rating_star_off_pressed_holo_light.png",
			"btn_rating_star_on_disabled_focused_holo_dark.png",
			"btn_rating_star_on_disabled_focused_holo_light.png",
			"btn_rating_star_on_disabled_holo_dark.png",
			"btn_rating_star_on_disabled_holo_light.png",
			"btn_rating_star_on_focused_holo_dark.png",
			"btn_rating_star_on_focused_holo_light.png",
			"btn_rating_star_on_normal_holo_dark.png",
			"btn_rating_star_on_normal_holo_light.png",
			"btn_rating_star_on_pressed_holo_dark.png",
			"btn_rating_star_on_pressed_holo_light.png",
			"btn_star_off_disabled_focused_holo_dark.png",
			"btn_star_off_disabled_focused_holo_light.png",
			"btn_star_off_disabled_holo_dark.png",
			"btn_star_off_disabled_holo_light.png",
			"btn_star_off_focused_holo_dark.png",
			"btn_star_off_focused_holo_light.png",
			"btn_star_off_normal_holo_dark.png",
			"btn_star_off_normal_holo_light.png",
			"btn_star_off_pressed_holo_dark.png",
			"btn_star_off_pressed_holo_light.png",
			"btn_star_on_disabled_focused_holo_dark.png",
			"btn_star_on_disabled_focused_holo_light.png",
			"btn_star_on_disabled_holo_dark.png",
			"btn_star_on_disabled_holo_light.png",
			"btn_star_on_focused_holo_dark.png",
			"btn_star_on_focused_holo_light.png",
			"btn_star_on_normal_holo_dark.png",
			"btn_star_on_normal_holo_light.png",
			"btn_star_on_pressed_holo_dark.png",
			"btn_star_on_pressed_holo_light.png",
			"btn_toggle_off_disabled_focused_holo_dark.9.png",
			"btn_toggle_off_disabled_focused_holo_light.9.png",
			"btn_toggle_off_disabled_holo_dark.9.png",
			"btn_toggle_off_disabled_holo_light.9.png",
			"btn_toggle_off_focused_holo_dark.9.png",
			"btn_toggle_off_focused_holo_light.9.png",
			"btn_toggle_off_normal_holo_dark.9.png",
			"btn_toggle_off_normal_holo_light.9.png",
			"btn_toggle_off_pressed_holo_dark.9.png",
			"btn_toggle_off_pressed_holo_light.9.png",
			"btn_toggle_on_disabled_focused_holo_dark.9.png",
			"btn_toggle_on_disabled_focused_holo_light.9.png",
			"btn_toggle_on_disabled_holo_dark.9.png",
			"btn_toggle_on_disabled_holo_light.9.png",
			"btn_toggle_on_focused_holo_dark.9.png",
			"btn_toggle_on_focused_holo_light.9.png",
			"btn_toggle_on_normal_holo_dark.9.png",
			"btn_toggle_on_normal_holo_light.9.png",
			"btn_toggle_on_pressed_holo_dark.9.png",
			"btn_toggle_on_pressed_holo_light.9.png",
			"day_picker_week_view_dayline_holo.9.png",
			"dialog_divider_horizontal_holo_dark.9.png",
			"dialog_divider_horizontal_holo_light.9.png",
			"dialog_ic_close_focused_holo_dark.png",
			"dialog_ic_close_focused_holo_light.png",
			"dialog_ic_close_normal_holo_dark.png",
			"dialog_ic_close_normal_holo_light.png",
			"dialog_ic_close_pressed_holo_dark.png",
			"dialog_ic_close_pressed_holo_light.png",
			"divider_horizontal_holo_dark.9.png",
			"divider_horizontal_holo_light.9.png", "divider_strong_holo.9.png",
			"divider_vertical_holo_dark.9.png",
			"divider_vertical_holo_light.9.png",
			"expander_close_holo_light.9.png", "expander_open_holo_dark.9.png",
			"expander_open_holo_light.9.png",
			"fastscroll_label_left_holo_dark.9.png",
			"fastscroll_label_left_holo_light.9.png",
			"fastscroll_label_right_holo_dark.9.png",
			"fastscroll_label_right_holo_light.9.png",
			"fastscroll_thumb_default_holo.png",
			"fastscroll_thumb_pressed_holo.png",
			"fastscroll_track_default_holo_dark.9.png",
			"fastscroll_track_default_holo_light.9.png",
			"fastscroll_track_pressed_holo_dark.9.png",
			"fastscroll_track_pressed_holo_light.9.png",
			/*
			 * "ic_ab_back_holo_dark.png", "ic_ab_back_holo_light.png",
			 * "ic_cab_done_holo.png", "ic_cab_done_holo_dark.png",
			 * "ic_cab_done_holo_light.png", "ic_checkmark_holo_light.png",
			 */
			"ic_dialog_alert_holo_dark.png", "ic_dialog_alert_holo_light.png",
			"ic_dialog_close_normal_holo.png",
			"ic_dialog_close_pressed_holo.png", "ic_dialog_focused_holo.png",
			"ic_find_next_holo_dark.png", "ic_find_next_holo_light.png",
			"ic_find_previous_holo_dark.png",
			"ic_find_previous_holo_light.png",
			"indicator_code_lock_point_area_default_holo.png",
			"indicator_code_lock_point_area_green_holo.png",
			"indicator_code_lock_point_area_red_holo.png",
			"list_activated_holo.9.png",
			"list_divider_horizontal_holo_dark.9.png",
			"list_longpressed_holo.9.png", "list_pressed_holo_dark.9.png",
			"list_pressed_holo_light.9.png",
			"list_section_divider_holo_dark.9.png",
			"list_section_divider_holo_light.9.png",
			"list_section_header_holo_dark.9.png",
			"list_section_header_holo_light.9.png",
			"list_selected_holo_dark.9.png", "list_selected_holo_light.9.png",
			"list_selector_activated_holo_dark.9.png",
			"list_selector_activated_holo_light.9.png",
			"list_selector_focused_holo_dark.9.png",
			"list_selector_focused_holo_light.9.png",
			"list_selector_multiselect_holo_dark.9.png",
			"list_selector_multiselect_holo_light.9.png",
			"list_selector_pressed_holo_dark.9.png",
			"list_selector_pressed_holo_light.9.png",
			"popup_inline_error_above_holo_dark.9.png",
			"popup_inline_error_above_holo_light.9.png",
			"popup_inline_error_holo_dark.9.png",
			"popup_inline_error_holo_light.9.png",
			"progress_primary_holo_dark.9.png",
			"progress_primary_holo_light.9.png",
			"progress_secondary_holo_dark.9.png",
			"progress_secondary_holo_light.9.png",
			"progressbar_indeterminate_holo1.png",
			"progressbar_indeterminate_holo2.png",
			"progressbar_indeterminate_holo3.png",
			"progressbar_indeterminate_holo4.png",
			"progressbar_indeterminate_holo5.png",
			"progressbar_indeterminate_holo6.png",
			"progressbar_indeterminate_holo7.png",
			"progressbar_indeterminate_holo8.png",
			"quickactions_arrowdown_left_holo_dark.9.png",
			"quickactions_arrowdown_left_holo_light.9.png",
			"quickactions_arrowdown_right_holo_dark.9.png",
			"quickactions_arrowdown_right_holo_light.9.png",
			"quickactions_arrowup_left_holo_dark.9.png",
			"quickactions_arrowup_left_holo_light.9.png",
			"quickactions_arrowup_left_right_holo_dark.9.png",
			"quickactions_arrowup_right_holo_light.9.png",
			"rate_star_big_half_holo_dark.png",
			"rate_star_big_half_holo_light.png",
			"rate_star_big_off_holo_dark.png",
			"rate_star_big_off_holo_light.png",
			"rate_star_big_on_holo_dark.png",
			"rate_star_big_on_holo_light.png",
			"rate_star_med_half_holo_dark.png",
			"rate_star_med_half_holo_light.png",
			"rate_star_med_off_holo_dark.png",
			"rate_star_med_off_holo_light.png",
			"rate_star_med_on_holo_dark.png",
			"rate_star_med_on_holo_light.png",
			"rate_star_small_half_holo_dark.png",
			"rate_star_small_half_holo_light.png",
			"rate_star_small_off_holo_dark.png",
			"rate_star_small_off_holo_light.png",
			"rate_star_small_on_holo_dark.png",
			"rate_star_small_on_holo_light.png",
			"scrollbar_handle_holo_dark.9.png",
			"scrollbar_handle_holo_light.9.png",
			"scrubber_control_disabled_holo.png",
			"scrubber_control_focused_holo.png",
			"scrubber_control_normal_holo.png",
			"scrubber_control_pressed_holo.png", "scrubber_primary_holo.9.png",
			"scrubber_secondary_holo.9.png", "scrubber_track_holo_dark.9.png",
			"scrubber_track_holo_light.9.png", "spinner_16_inner_holo.png",
			"spinner_16_outer_holo.png", "spinner_20_inner_holo.png",
			"spinner_20_outer_holo.png", "spinner_48_inner_holo.png",
			"spinner_48_outer_holo.png", "spinner_76_inner_holo.png",
			"spinner_76_outer_holo.png", "spinner_ab_default_holo_dark.9.png",
			"spinner_ab_default_holo_light.9.png",
			"spinner_ab_disabled_holo_dark.9.png",
			"spinner_ab_disabled_holo_light.9.png",
			"spinner_ab_focused_holo_dark.9.png",
			"spinner_ab_focused_holo_light.9.png",
			"spinner_ab_pressed_holo_dark.9.png",
			"spinner_ab_pressed_holo_light.9.png",
			"spinner_default_holo_dark.9.png",
			"spinner_default_holo_light.9.png",
			"spinner_disabled_holo_dark.9.png",
			"spinner_disabled_holo_light.9.png",
			"spinner_focused_holo_dark.9.png",
			"spinner_focused_holo_light.9.png",
			"spinner_pressed_holo_dark.9.png",
			"spinner_pressed_holo_light.9.png",
			"switch_bg_disabled_holo_dark.9.png",
			"switch_bg_disabled_holo_light.9.png",
			"switch_bg_focused_holo_dark.9.png",
			"switch_bg_focused_holo_light.9.png", "switch_bg_holo_dark.9.png",
			"switch_bg_holo_light.9.png",
			"switch_thumb_activated_holo_dark.9.png",
			"switch_thumb_activated_holo_light.9.png",
			"switch_thumb_disabled_holo_dark.9.png",
			"switch_thumb_disabled_holo_light.9.png",
			"switch_thumb_holo_dark.9.png", "switch_thumb_holo_light.9.png",
			"switch_thumb_pressed_holo_dark.9.png",
			"switch_thumb_pressed_holo_light.9.png",
			"sym_keyboard_return_holo.png", "tab_bottom_holo.9.png",
			"tab_pressed_holo.9.png", "tab_selected_focused_holo.9.png",
			"tab_selected_holo.9.png", "tab_selected_pressed_holo.9.png",
			"tab_unselected_focused_holo.9.png", "tab_unselected_holo.9.png",
			"tab_unselected_pressed_holo.9.png",
			"textfield_activated_holo_dark.9.png",
			"textfield_activated_holo_light.9.png",
			"textfield_bg_activated_holo_dark.9.png",
			"textfield_bg_default_holo_dark.9.png",
			"textfield_bg_disabled_focused_holo_dark.9.png",
			"textfield_bg_disabled_holo_dark.9.png",
			"textfield_bg_focused_holo_dark.9.png",
			"textfield_default_holo_dark.9.png",
			"textfield_default_holo_light.9.png",
			"textfield_disabled_focused_holo_dark.9.png",
			"textfield_disabled_focused_holo_light.9.png",
			"textfield_disabled_holo_dark.9.png",
			"textfield_disabled_holo_light.9.png",
			"textfield_focused_holo_dark.9.png",
			"textfield_focused_holo_light.9.png",
			"textfield_longpress_holo.9.png",
			"textfield_multiline_activated_holo_dark.9.png",
			"textfield_multiline_activated_holo_light.9.png",
			"textfield_multiline_default_holo_dark.9.png",
			"textfield_multiline_default_holo_light.9.png",
			"textfield_multiline_disabled_focused_holo_dark.9.png",
			"textfield_multiline_disabled_focused_holo_light.9.png",
			"textfield_multiline_disabled_holo_dark.9.png",
			"textfield_multiline_disabled_holo_light.9.png",
			"textfield_multiline_focused_holo_dark.9.png",
			"textfield_multiline_focused_holo_light.9.png",
			"textfield_pressed_holo.9.png",
			"textfield_search_default_holo_dark.9.png",
			"textfield_search_default_holo_light.9.png",
			"textfield_search_right_default_holo_dark.9.png",
			"textfield_search_right_default_holo_light.9.png",
			"textfield_search_right_selected_holo_dark.9.png",
			"textfield_search_right_selected_holo_light.9.png",
			"textfield_search_selected_holo_dark.9.png",
			"textfield_search_selected_holo_light.9.png",
			"btn_cling_normal.9.png", "btn_cling_pressed.9.png", "cling.png",
			"focused_bg.9.png", "grid_focused.9.png", "grid_pressed.9.png",
			"grid_selected.9.png", "homescreen_blue_normal_holo.9.png",
			"homescreen_blue_strong_holo.9.png", "hotseat_scrubber_holo.9.png",
			"ic_launcher_info_active_holo.png",
			"widget_resize_frame_holo.9.png",
			"widget_resize_handle_bottom.png", "widget_resize_handle_left.png",
			"widget_resize_handle_right.png", "widget_resize_handle_top.png",
			"overscroll_glow_left.9.png", "overscroll_glow_right.9.png",
			"page_hover_left_holo.9.png", "page_hover_right_holo_9.png",
			"paged_view_indicator.9.png", "portal_ring_outer_holo.png",
			"portal_ring_rest.png", "tab_selected_focused_holo.9.png",
			"tab_selected_holo.9.png",
			"tab_selected_pressed_focused_holo.9.png",
			"tab_selected_pressed_holo_9.png",
			"tab_unselected_focused_holo.9.png", "tab_unselected_holo.9.png",
			"tab_unselected_pressed_focused_holo.9.png",
			"tab_unselected_pressed_holo.9.png", "top_slider.png",
			"ic_notify_clear_pressed.png", "ic_notify_open_pressed.png",
			"top_divider_glow.png", "bottom_divider_glow.png",
			"tab_click_bg.xml", "dividing_line.png",
			"ic_divider_dashed_holo_dark.png",
			"list_section_divider_holo_custom.9.png",
			"silent_mode_indicator.xml", "tab_selected_holo.9.png",
			"ic_recents_clear_pressed.png", "paged_view_indicator.9.png",
			"focused_bg.9.png", "grid_focused.9.png", "grid_pressed.9.png",
			"grid_selected.9.png", "homescreen_blue_normal_holo.9.png",
			"homescreen_blue_strong_holo.9.png",
			"appwidget_settings_ind_on_r_holo.9.png",
			"appwidget_settings_ind_off_l_holo.9.png",
			"tab_widget_indicator_selector.xml", "focusable_view_bg.xml",
			"overscroll_edge.png", "overscroll_glow.png",
			"appwidget_item_bg_pressed.9.png",
			"appwidget_inner_pressed_r_holo.9.png",
			"appwidget_inner_pressed_l_holo.9.png",
			"appwidget_inner_pressed_c_holo.9.png",
			"appwidget_inner_focused_c_holo.9.png",
			"appwidget_inner_focused_l_holo.9.png",
			"appwidget_inner_focused_r_holo.9.png",
			"appwidget_settings_ind_mid_c_holo.9.png",
			"appwidget_settings_ind_mid_l_holo.9.png",
			"appwidget_settings_ind_mid_r_holo.9.png",
			"appwidget_settings_ind_on_c_holo.9.png",
			"appwidget_settings_ind_on_l_holo.9.png",
			"appwidget_settings_ind_on_r_holo.9.png",
			"activated_background_holo_dark.xml",
			"activated_background_holo_light.xml", "cling_button_bg.xml",
			"ticker_background.xml", "ic_notify_clear",
			"activity_picker_bg_activated.9.png",
			"activity_picker_bg_focused.9.png",
			"text_select_handle_middle.png", "text_select_handle_right.png",
			"text_select_handle_left.png", "recents_thumbnail_bg_press.9.png",
			"recents_thumbnail_bg_dragging.9.png", "icholocolor.png",
			"kg_add_widget_pressed.png",
			"dropdown_disabled_focused_holo_dark.9.png",
			"dropdown_disabled_holo_dark.9.png",
			"dropdown_focused_holo_dark.9.png",
			"dropdown_normal_holo_dark.9.png",
			"dropdown_pressed_holo_dark.9.png",
			"expander_close_holo_dark.9.png", "expander_open_holo_dark.9.png",
			"list_divider_holo_light.9.png", "ab_transparent_dark_holo.9.png" };

	static String actionBarResources[] = { "ic_cab_done_holo_light.png",
			"ic_menu_selectall_holo_light.png", "ic_menu_cut_holo_light.png",
			"ic_menu_copy_holo_light.png" };

	public static boolean isActionbarRes(String str) {
		str = str.trim();
		if (str == null)
			return false;
		String[] arrays = str.split("/");
		if (arrays.length == 0)
			return false;

		str = arrays[arrays.length - 1];
		for (String res : actionBarResources)
			if (res.equals(str))
				return true;
		return false;
	}

	public static boolean isHoloRes(String str) {
		str = str.trim();
		if (str == null)
			return false;
		String[] arrays = str.split("/");
		if (arrays.length == 0)
			return false;

		str = arrays[arrays.length - 1];
		for (String res : HoloResources)
			if (res.equals(str))
				return true;
		return false;
	}

	public static boolean compare(String str, String compareResId) {
		str = str.trim();
		if (str == null)
			return false;
		String[] arrays = str.split("/");
		if (arrays.length == 0)
			return false;

		str = arrays[arrays.length - 1];
		if (str.equals(compareResId)) {
			return true;
		}
		return false;
	}

}