void glBlendEquationSeparateOES ( GLenum modeRGB, GLenum modeAlpha )
void glBlendFuncSeparateOES ( GLenum srcRGB, GLenum dstRGB, GLenum srcAlpha, GLenum dstAlpha )
void glBlendEquationOES ( GLenum mode )
void glDrawTexsOES ( GLshort x, GLshort y, GLshort z, GLshort width, GLshort height )
void glDrawTexiOES ( GLint x, GLint y, GLint z, GLint width, GLint height )
void glDrawTexxOES ( GLfixed x, GLfixed y, GLfixed z, GLfixed width, GLfixed height )
void glDrawTexsvOES ( const GLshort *coords )
void glDrawTexivOES ( const GLint *coords )
void glDrawTexxvOES ( const GLfixed *coords )
void glDrawTexfOES ( GLfloat x, GLfloat y, GLfloat z, GLfloat width, GLfloat height )
void glDrawTexfvOES ( const GLfloat *coords )
void glEGLImageTargetTexture2DOES ( GLenum target, GLeglImageOES image )
void glEGLImageTargetRenderbufferStorageOES ( GLenum target, GLeglImageOES image )
void glAlphaFuncxOES ( GLenum func, GLclampx ref )
void glClearColorxOES ( GLclampx red, GLclampx green, GLclampx blue, GLclampx alpha )
void glClearDepthxOES ( GLclampx depth )
void glClipPlanexOES ( GLenum plane, const GLfixed *equation )
void glColor4xOES ( GLfixed red, GLfixed green, GLfixed blue, GLfixed alpha )
void glDepthRangexOES ( GLclampx zNear, GLclampx zFar )
void glFogxOES ( GLenum pname, GLfixed param )
void glFogxvOES ( GLenum pname, const GLfixed *params )
void glFrustumxOES ( GLfixed left, GLfixed right, GLfixed bottom, GLfixed top, GLfixed zNear, GLfixed zFar )
void glGetClipPlanexOES ( GLenum pname, GLfixed *eqn )
void glGetFixedvOES ( GLenum pname, GLfixed *params )
void glGetLightxvOES ( GLenum light, GLenum pname, GLfixed *params )
void glGetMaterialxvOES ( GLenum face, GLenum pname, GLfixed *params )
void glGetTexEnvxvOES ( GLenum env, GLenum pname, GLfixed *params )
void glGetTexParameterxvOES ( GLenum target, GLenum pname, GLfixed *params )
void glLightModelxOES ( GLenum pname, GLfixed param )
void glLightModelxvOES ( GLenum pname, const GLfixed *params )
void glLightxOES ( GLenum light, GLenum pname, GLfixed param )
void glLightxvOES ( GLenum light, GLenum pname, const GLfixed *params )
void glLineWidthxOES ( GLfixed width )
void glLoadMatrixxOES ( const GLfixed *m )
void glMaterialxOES ( GLenum face, GLenum pname, GLfixed param )
void glMaterialxvOES ( GLenum face, GLenum pname, const GLfixed *params )
void glMultMatrixxOES ( const GLfixed *m )
void glMultiTexCoord4xOES ( GLenum target, GLfixed s, GLfixed t, GLfixed r, GLfixed q )
void glNormal3xOES ( GLfixed nx, GLfixed ny, GLfixed nz )
void glOrthoxOES ( GLfixed left, GLfixed right, GLfixed bottom, GLfixed top, GLfixed zNear, GLfixed zFar )
void glPointParameterxOES ( GLenum pname, GLfixed param )
void glPointParameterxvOES ( GLenum pname, const GLfixed *params )
void glPointSizexOES ( GLfixed size )
void glPolygonOffsetxOES ( GLfixed factor, GLfixed units )
void glRotatexOES ( GLfixed angle, GLfixed x, GLfixed y, GLfixed z )
void glSampleCoveragexOES ( GLclampx value, GLboolean invert )
void glScalexOES ( GLfixed x, GLfixed y, GLfixed z )
void glTexEnvxOES ( GLenum target, GLenum pname, GLfixed param )
void glTexEnvxvOES ( GLenum target, GLenum pname, const GLfixed *params )
void glTexParameterxOES ( GLenum target, GLenum pname, GLfixed param )
void glTexParameterxvOES ( GLenum target, GLenum pname, const GLfixed *params )
void glTranslatexOES ( GLfixed x, GLfixed y, GLfixed z )
GLboolean glIsRenderbufferOES ( GLuint renderbuffer )
void glBindRenderbufferOES ( GLenum target, GLuint renderbuffer )
void glDeleteRenderbuffersOES ( GLsizei n, const GLuint *renderbuffers )
void glGenRenderbuffersOES ( GLsizei n, GLuint *renderbuffers )
void glRenderbufferStorageOES ( GLenum target, GLenum internalformat, GLsizei width, GLsizei height )
void glGetRenderbufferParameterivOES ( GLenum target, GLenum pname, GLint *params )
GLboolean glIsFramebufferOES ( GLuint framebuffer )
void glBindFramebufferOES ( GLenum target, GLuint framebuffer )
void glDeleteFramebuffersOES ( GLsizei n, const GLuint *framebuffers )
void glGenFramebuffersOES ( GLsizei n, GLuint *framebuffers )
GLenum glCheckFramebufferStatusOES ( GLenum target )
void glFramebufferRenderbufferOES ( GLenum target, GLenum attachment, GLenum renderbuffertarget, GLuint renderbuffer )
void glFramebufferTexture2DOES ( GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level )
void glGetFramebufferAttachmentParameterivOES ( GLenum target, GLenum attachment, GLenum pname, GLint *params )
void glGenerateMipmapOES ( GLenum target )
// Hard to export to Java:
// void *glMapBufferOES ( GLenum target, GLenum access )
// GLboolean glUnmapBufferOES ( GLenum target )
// void glGetBufferPointervOES ( GLenum target, GLenum pname, void **params )
void glCurrentPaletteMatrixOES ( GLuint matrixpaletteindex )
void glLoadPaletteFromModelViewMatrixOES ( void )
void glMatrixIndexPointerOES ( GLint size, GLenum type, GLsizei stride, const GLvoid *pointer )
void glWeightPointerOES ( GLint size, GLenum type, GLsizei stride, const GLvoid *pointer )
void glDepthRangefOES ( GLclampf zNear, GLclampf zFar )
void glFrustumfOES ( GLfloat left, GLfloat right, GLfloat bottom, GLfloat top, GLfloat zNear, GLfloat zFar )
void glOrthofOES ( GLfloat left, GLfloat right, GLfloat bottom, GLfloat top, GLfloat zNear, GLfloat zFar )
void glClipPlanefOES ( GLenum plane, const GLfloat *equation )
void glGetClipPlanefOES ( GLenum pname, GLfloat *eqn )
void glClearDepthfOES ( GLclampf depth )
void glTexGenfOES ( GLenum coord, GLenum pname, GLfloat param )
void glTexGenfvOES ( GLenum coord, GLenum pname, const GLfloat *params )
void glTexGeniOES ( GLenum coord, GLenum pname, GLint param )
void glTexGenivOES ( GLenum coord, GLenum pname, const GLint *params )
void glTexGenxOES ( GLenum coord, GLenum pname, GLfixed param )
void glTexGenxvOES ( GLenum coord, GLenum pname, const GLfixed *params )
void glGetTexGenfvOES ( GLenum coord, GLenum pname, GLfloat *params )
void glGetTexGenivOES ( GLenum coord, GLenum pname, GLint *params )
void glGetTexGenxvOES ( GLenum coord, GLenum pname, GLfixed *params )
