#!/bin/bash
# Copyright (C) 2024 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# "Fake" ravenizer, which just copies the file.
# We need it to add ravenizer support to Soong on AOSP,
# when the actual ravenizer is not in AOSP yet.

invalid_arg() {
    echo "Ravenizer(fake): invalid args" 1>&2
    exit 1
}

(( $# >= 4 )) || invalid_arg
[[ "$1" == "--in-jar" ]] || invalid_arg
[[ "$3" == "--out-jar" ]] || invalid_arg

echo "Ravenizer(fake): copiyng $2 to $4"

cp "$2" "$4"
