#! /bin/sh
#
# Copyright (C) 2008 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

./glapigen ../../include/GLES/gl.h > ../GLES_CM/gl_api.in 
./glentrygen ../../include/GLES/gl.h > ../gl_entries.in 
./glapigen ../../include/GLES/glext.h > ../GLES_CM/glext_api.in 
./glentrygen ../../include/GLES/glext.h > ../glext_entries.in 
