#! /usr/bin/perl
#
# Copyright (C) 2010 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

use strict;

my %enumHash = ();

while (my $line = <STDIN>) {
  next if $line =~ /^\//;
  # Skip bitfield definitions.
  next if $line =~ /_BIT(\d+_|\s+)/;
  if ($line !~ /^#define\s+(\S+)\s+(0x\S+)/) {
    next;
  }
  my $enumName = $1;
  my $enumValue = $2;
  next if exists($enumHash { $enumValue });
  $enumHash { $enumValue } = $enumName;
  printf("GL_ENUM(%s,%s)\n", $enumValue, $enumName);
}





