#!/system/bin/sh
#
# Script to start "hid" on the device, which has a very rudimentary
# shell.
#
base=/system
export CLASSPATH=$base/framework/hid.jar
exec app_process $base/bin com.android.commands.hid.Hid "$@"
