#!/bin/bash
#
# Copyright (C) 2014 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

set -e

PATH_TO_FRAMEWORK_RES=${ANDROID_BUILD_TOP}/prebuilts/sdk/current/android.jar

aapt2 compile --dir res -o compiled.flata
aapt2 link \
    -I $PATH_TO_FRAMEWORK_RES \
    --manifest AndroidManifest.xml \
    -A assets \
    --split basic_hdpi-v4.apk:hdpi \
    --split basic_xhdpi-v4.apk:xhdpi \
    --split basic_xxhdpi-v4.apk:xxhdpi \
    --split basic_de_fr.apk:de,fr \
    -o basic.apk \
    compiled.flata
rm compiled.flata
