#!/bin/bash
#
# Copyright (C) 2014 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

set -e

PATH_TO_FRAMEWORK_RES=${ANDROID_BUILD_TOP}/prebuilts/sdk/current/public/android.jar
PATH_TO_LIB_ONE=../lib_one/lib_one.apk
PATH_TO_LIB_TWO=../lib_two/lib_two.apk

aapt package \
    -M AndroidManifest.xml \
    -S res \
    -I $PATH_TO_FRAMEWORK_RES \
    -I $PATH_TO_LIB_ONE \
    -I $PATH_TO_LIB_TWO \
    -F libclient.apk -f
